# usb requests
HELLO = 0
GENERAL_CMD = 1
TERMINAL_CMD = 2
DOWNLOAD_FILE = 3
UPLOAD_FILE = 4
GET_PROGRAM_STATE = 5
GET_NAME = 6
GET_FIRMWARE_VERSION = 7
GET_BOOTLOADER_VERSION = 8
GET_HARDWARE_VERSION = 9
GET_BATTERY_VOLTAGE = 11

# general commands
CMD_START = 1
CMD_STOP = 2
CMD_REBOOT = 3

